Improvement - "Adding new features for table component"
scania/corporate-ui pull request #576
Opened 2020-08-11 19:46 UTC by gustavookamoto

While I was implementing the table component, I realise some improvements that would be good to have it:
- Hover optinon with event emitter (as edit and delete options)
- Clear fields with "cross-icon" inside inputs.
- Code review

![image](https://user-images.githubusercontent.com/55094504/89941561-9284cf00-dbf1-11ea-8606-97f0560cb966.png)

2020-09-03 10:43 UTC, helloimela commented
Fix #576

2020-09-17 10:40 UTC, helloimela commented
Hi, thanks for the PR!
I got this error when trying out this solution. When I typed on input, it does not do the filter and this error appears. 
Do you know why this happen?
![image](https://user-images.githubusercontent.com/1199101/93459887-b4edc480-f8e2-11ea-9961-3f4533e8886e.png)
![image](https://user-images.githubusercontent.com/1199101/93460064-0007d780-f8e3-11ea-8035-66108daaf75f.png)

2020-09-17 11:26 UTC, helloimela requested changes

2020-09-17 11:26 UTC, helloimela commented on src/components/table/table.tsx
> +    let actives = document.querySelectorAll(".sort-active");
This should also use shadow root selector

2020-10-08 06:38 UTC, mmexvr commented
@gustavookamoto FYI

2020-10-16 12:04 UTC, helloimela approved these changes
Looks good!

2020-10-16 12:06 UTC, merged